### ISSUE TITLE
Add support for markdown files

### ISSUE THREAD

**Issue by dhillonks** [ritikbheda/commandline-ssg#8]
### Description
Currently, the tool only supports `.txt` files. The file handling should be expanded to also include `.md` files. Markdown is similar to plain text files but allows for simple formatting and structure to be applied to the document.

As this is the initial supporting feature for markdown, only one of the markdown features will be implemented. And as a starting point, this would be the **bold** markdown syntax. This would mean that text enclosed with `**` or `__` would be rendered in HTML using `<strong>` tag. 

#### For example:
`**bold**` or `__bold__` would become `<strong>bold</strong>`

## To-do
- [ ] Modify file handling to support both `.txt` and `.md` files
- [ ] `.txt` files should still be parsed in the same way after this change
- [ ] `.md` files should processed to support the **bold** markdown syntax.
